services:
  jupyter:
    container_name: jupyter-pyspark
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"

  db:
    container_name: postgres_db
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  mage:
    container_name: mage
    command: mage start ${PROJECT_NAME}
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    env_file:
      - .env
    #environment:

    ports:
      - "6789:6789"
    volumes:
       - ./orchestrator:/home/src/
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"
    
volumes:
  postgres-data:
